version: '3.4'

services:
  postgres:
    image: postgres
    container_name: todo_postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password